### ISSUE TITLE
Show organizations (including role) for a user and allow them to manage it

### ISSUE THREAD

**Issue by avaliani** [karma-exchange-org/karma-exchange#160]
Show organizations that a user belongs to. If they are an admin or organizer show a special label next to that organization. This information is available in the USER resource (you don't need to do a query).

See field "organizationMemberships" which is a list of OrganizationMembership. You only need to look at the sub-fields "organization", "role", and "requestedRole". The other fields were added to support member querying by role.

``` java
  @Embed
  @Data
  @NoArgsConstructor
  public static final class OrganizationMembership {
    private KeyWrapper<Organization> organization;
    @Nullable
    private Organization.Role role;
    @Nullable
    private Organization.Role requestedRole;
...
  }
```

Also allow users that are not admins to leave any organization they are currently a member of. Make sure the flow is seamless if the user is an admin also. Meaning admins should be able to leave an organization but they can also manage members (haven't really thought too much about the UI).

Note that support for adding membership based on domain is in an upcoming pull request. Will update you later on tonight on that.

**Comment by hbalijepalli** [comment]
Can you get me atleast Org Name, Facebook ID? This will help me put a name and a image without re-querying backend.

**Comment by avaliani** [comment]
Sure. There are now two apis for querying org info:

```
GET /api/user/{user_key}/org
```

or

```
GET /api/me/org
```

Relevant parts of the organization have been fetched for the view (including causes, karma points, etc).

Note that the list includes active memberships and pending memberships.

Just to make sure we're on the same page, my thought was that **pending memberships should only be visible to the current user.** Whereas active / granted memberships can be visible to all users.

``` java
public class OrganizationMembershipView {

  private KeyWrapper<Organization> org;
  private String orgName;
  private PageRef orgPage;
  private long orgKarmaPoints;
  private AggregateRating orgEventRating;
  private List<KeyWrapper<CauseType>> orgCauses;

  @Nullable
  private Organization.Role role;
  @Nullable
  private Organization.Role requestedRole;
...
}
```
