### ISSUE TITLE
Organizers should be able to see the event detail view

### ISSUE THREAD

**Issue by avaliani** [karma-exchange-org/karma-exchange#73]
Current organizers are only allowed to edit events. They can't see the event detail view. Editing should be a button from the event detail view. Organizers may just want to comment on the logistics etc.

**Comment by hbalijepalli** [comment]
I added view event button to event detail. Should we remove Edit event button on the event detail?

**Comment by avaliani** [comment]
Yeah. I think removing the "edit event" button from the event search details would be good. It should only be in the event page itself (for organizers only of course).

Maybe we should also rename "more information" to "view details". That way it's universal to organizers and participants?

**Comment by hbalijepalli** [comment]
Fixed the issue.
