### ISSUE TITLE
Start and end time should be visible in user profile view

### ISSUE THREAD

**Issue by avaliani** [karma-exchange-org/karma-exchange#94]
In the user profile view it says 

June 14th, 2013 <Event Title> at <Location>

Instead it should say

June 14th, 2013 from 5:00 pm to 6:00 pm <Event Title> at <Location>

Also... I'd try to keep the indentation consistent. So the dates at the very least line up. And ideally even the times.

**Comment by hbalijepalli** [comment]
Fixed in #114
