### ISSUE TITLE
Event registration UI consistency

### ISSUE THREAD

**Issue by avaliani** [karma-exchange-org/karma-exchange#97]
Example:
  a. if you register for an event on the event search screen 
  b. then click on more info. 

You see you're registered, but your image doesn't show up in the side bar.

Note sure if this is due to eventual consistency simulation or due to using a cached event object. Please investigate alternatives to implementing this including modifying the cached event object if any (though in this case you shouldn't be doing that and instead should be using the expanded event search view).

**Comment by hbalijepalli** [comment]
Not a bug. It is due to eventual consistency. Verified.
