### ISSUE TITLE
Newlines in event description (and perhaps elsewhere) are not retained

### ISSUE THREAD

**Issue by avaliani** [karma-exchange-org/karma-exchange#99]
Newlines in the event description should be converted to &lt;br&gt; or whatever is appropriate.

I assume if less than ("<") is being used in the description it's not being escaped out either. All the text needs to be escaped out also.

See the description of the test events.
/bootstrap/test_resources
L177 - org.karmaexchange.bootstrap.TestResourcesBootstrapTask.java
"throughout the week.\n\n"

**Comment by hbalijepalli** [comment]
Fixed in pull request #110
